[[apps]]
name = "Firefox"
exec = "firefox"
icon = "firefox"
category = "Internet"

[[apps]]
name = "VLC Media Player"
exec = "vlc"
icon = "vlc"
category = "Media"

[[apps]]
name = "Steam"
exec = "steam"
icon = "steam"
category = "Games"

[[apps]]
name = "Discord"
exec = "discord"
icon = "discord"
category = "Communication"

[[apps]]
name = "TIDAL Hi-Fi"
exec = "tidal-hifi"
icon = "TIDAL_Hi-Fi"
category = "Media"

[[apps]]
name = "Netflix"
exec = "firefox https://netflix.com"
icon = "default"
category = "Streaming"

[[apps]]
name = "YouTube"
exec = "firefox https://youtube.com"
icon = "default"
category = "Streaming"

[[apps]]
name = "Spotify Web"
exec = "firefox https://open.spotify.com"
icon = "default"
category = "Music"

[[apps]]
name = "Proton Mail"
exec = "protonmail-desktop"
icon = "Proton_Mail"
category = "Communication"

[[apps]]
name = "Designer"
exec = "designer"
icon = "designer"
category = "Graphics"

[[apps]]
name = "Pinta"
exec = "pinta"
icon = "pinta"
category = "Graphics"

[[apps]]
name = "MakeMKV"
exec = "makemkv"
icon = "makemkv"
category = "Media"

[[apps]]
name = "Zed Editor"
exec = "zed"
icon = "zed"
category = "Development"