# GJTV Keymap Configuration
# Define key bindings for navigation and actions

[navigation]
# Basic movement
up = "ArrowUp"
down = "ArrowDown"
left = "ArrowLeft"
right = "ArrowRight"

# Alternative movement (WASD)
up_alt = "KeyW"
down_alt = "KeyS"
left_alt = "KeyA"
right_alt = "KeyD"

# Vim-style movement
up_vim = "KeyK"
down_vim = "KeyJ"
left_vim = "KeyH"
right_vim = "KeyL"

# Tab navigation
next_tab = "Tab"
prev_tab = "ShiftLeft+Tab"
tab_1 = "Digit1"
tab_2 = "Digit2"
tab_3 = "Digit3"
tab_4 = "Digit4"
tab_5 = "Digit5"

[actions]
# Core actions
launch = "Enter"
launch_alt = "Space"
back = "Escape"
exit = "KeyQ"

# Settings and configuration
settings = "KeyM"
toggle_fullscreen = "F11"
reload_config = "F5"

# Application management
close_app = "KeyC"
force_quit = "ControlLeft+KeyC"
restart_app = "KeyR"

[scrolling]
# Page navigation
page_up = "PageUp"
page_down = "PageDown"
home = "Home"
end = "End"

# Fast scrolling
scroll_up_fast = "ControlLeft+ArrowUp"
scroll_down_fast = "ControlLeft+ArrowDown"

[gamepad]
# Xbox/PlayStation controller mapping
# D-pad
dpad_up = "GamepadDPadUp"
dpad_down = "GamepadDPadDown"
dpad_left = "GamepadDPadLeft"
dpad_right = "GamepadDPadRight"

# Face buttons
launch_gamepad = "GamepadButtonSouth"    # A/X button
back_gamepad = "GamepadButtonEast"       # B/Circle button
settings_gamepad = "GamepadButtonWest"   # X/Square button
menu_gamepad = "GamepadButtonNorth"      # Y/Triangle button

# Shoulder buttons
next_tab_gamepad = "GamepadButtonRightShoulder"
prev_tab_gamepad = "GamepadButtonLeftShoulder"

# Triggers
launch_trigger = "GamepadButtonRightTrigger"

# Analog sticks
stick_deadzone = 0.2
stick_sensitivity = 1.0

[remote_control]
# TV remote / IR remote control codes
# These are example codes - adjust for your specific remote
home_button = "Home"
ok_button = "Enter"
back_button = "Escape"
menu_button = "KeyM"

# Navigation
remote_up = "ArrowUp"
remote_down = "ArrowDown"
remote_left = "ArrowLeft"
remote_right = "ArrowRight"

# Media keys
play_pause = "MediaPlayPause"
stop = "MediaStop"
volume_up = "AudioVolumeUp"
volume_down = "AudioVolumeDown"
mute = "AudioVolumeMute"

# Number keys for direct selection
select_1 = "Digit1"
select_2 = "Digit2"
select_3 = "Digit3"
select_4 = "Digit4"
select_5 = "Digit5"
select_6 = "Digit6"
select_7 = "Digit7"
select_8 = "Digit8"
select_9 = "Digit9"
select_0 = "Digit0"

[accessibility]
# High contrast mode toggle
high_contrast = "ControlLeft+ShiftLeft+KeyH"

# Large text mode
large_text = "ControlLeft+Plus"
small_text = "ControlLeft+Minus"

# Voice control (if implemented)
voice_activation = "ControlLeft+ShiftLeft+KeyV"

# Screen reader compatibility
announce_selection = "ControlLeft+ShiftLeft+KeyA"

[developer]
# Debug and development keys
debug_mode = "F12"
reload_ui = "ControlLeft+KeyR"
show_fps = "ControlLeft+ShiftLeft+KeyF"
screenshot = "F9"

# Console access
toggle_console = "Grave"  # ` key
clear_console = "ControlLeft+KeyL"

[custom]
# User-defined custom key bindings
# Add your own custom mappings here
# Example:
# custom_action_1 = "ControlLeft+KeyX"
# custom_action_2 = "ShiftLeft+KeyZ"

[modifiers]
# Modifier key behavior
ctrl_repeat_rate = 50      # milliseconds
shift_hold_time = 500      # milliseconds
alt_double_tap = true      # enable alt double-tap detection

[timing]
# Input timing configuration
key_repeat_delay = 250     # milliseconds before repeat starts
key_repeat_rate = 50       # milliseconds between repeats
double_click_time = 300    # milliseconds for double-click detection
hold_time = 800           # milliseconds to register as "hold"