# GJTV Theme Configuration
# Define color schemes and visual themes

[default]
name = "GJTV Default"
description = "Default dark theme with warm accents"
background_color = "2E282A"
text_color = "FFFFFF" 
selected_color = "D6BA73"
secondary_color = "4A4A4A"
accent_color = "D6BA73"
error_color = "E06C75"
success_color = "98C379"
warning_color = "E5C07B"

[dark_blue]
name = "Dark Blue"
description = "Professional dark blue theme"
background_color = "1E1E2E"
text_color = "CDD6F4"
selected_color = "89B4FA"
secondary_color = "313244"
accent_color = "89B4FA"
error_color = "F38BA8"
success_color = "A6E3A1"
warning_color = "F9E2AF"

[nord]
name = "Nord"
description = "Nord color scheme inspired theme"
background_color = "2E3440"
text_color = "ECEFF4"
selected_color = "88C0D0"
secondary_color = "3B4252"
accent_color = "5E81AC"
error_color = "BF616A"
success_color = "A3BE8C"
warning_color = "EBCB8B"

[dracula]
name = "Dracula"
description = "Popular Dracula theme colors"
background_color = "282A36"
text_color = "F8F8F2"
selected_color = "BD93F9"
secondary_color = "44475A"
accent_color = "FF79C6"
error_color = "FF5555"
success_color = "50FA7B"
warning_color = "F1FA8C"

[gruvbox_dark]
name = "Gruvbox Dark"
description = "Warm and cozy Gruvbox dark theme"
background_color = "282828"
text_color = "EBDBB2"
selected_color = "FABD2F"
secondary_color = "3C3836"
accent_color = "FE8019"
error_color = "FB4934"
success_color = "B8BB26"
warning_color = "FABD2F"

[catppuccin_mocha]
name = "Catppuccin Mocha"
description = "Soothing pastel theme"
background_color = "1E1E2E"
text_color = "CDD6F4"
selected_color = "F5C2E7"
secondary_color = "313244"
accent_color = "CBA6F7"
error_color = "F38BA8"
success_color = "A6E3A1"
warning_color = "F9E2AF"

[tokyo_night]
name = "Tokyo Night"
description = "Modern Tokyo Night theme"
background_color = "1A1B26"
text_color = "C0CAF5"
selected_color = "7AA2F7"
secondary_color = "24283B"
accent_color = "BB9AF7"
error_color = "F7768E"
success_color = "9ECE6A"
warning_color = "E0AF68"

[solarized_dark]
name = "Solarized Dark"
description = "Classic Solarized dark theme"
background_color = "002B36"
text_color = "839496"
selected_color = "268BD2"
secondary_color = "073642"
accent_color = "2AA198"
error_color = "DC322F"
success_color = "859900"
warning_color = "B58900"

[high_contrast]
name = "High Contrast"
description = "High contrast theme for accessibility"
background_color = "000000"
text_color = "FFFFFF"
selected_color = "FFFF00"
secondary_color = "333333"
accent_color = "00FFFF"
error_color = "FF0000"
success_color = "00FF00"
warning_color = "FFAA00"

[light]
name = "Light Theme"
description = "Clean light theme for bright environments"
background_color = "FFFFFF"
text_color = "2E3440"
selected_color = "5E81AC"
secondary_color = "ECEFF4"
accent_color = "88C0D0"
error_color = "BF616A"
success_color = "A3BE8C"
warning_color = "D08770"

[gaming]
name = "Gaming RGB"
description = "Vibrant gaming-inspired theme"
background_color = "0D1117"
text_color = "F0F6FC"
selected_color = "00D8FF"
secondary_color = "21262D"
accent_color = "FF6B6B"
error_color = "FF4757"
success_color = "2ED573"
warning_color = "FFA502"

[retro]
name = "Retro CRT"
description = "Nostalgic retro computer theme"
background_color = "001100"
text_color = "00FF41"
selected_color = "FFFF00"
secondary_color = "003300"
accent_color = "00FFFF"
error_color = "FF4444"
success_color = "44FF44"
warning_color = "FFAA00"

[ocean]
name = "Ocean Blue"
description = "Calming ocean-inspired theme"
background_color = "0F3460"
text_color = "E8F4FD"
selected_color = "16537E"
secondary_color = "1E5F8A"
accent_color = "5DADE2"
error_color = "E74C3C"
success_color = "27AE60"
warning_color = "F39C12"

[sunset]
name = "Sunset Orange"
description = "Warm sunset colors"
background_color = "2C1810"
text_color = "F4E7DA"
selected_color = "FF6B35"
secondary_color = "4A2C1A"
accent_color = "FF8C42"
error_color = "E85A4F"
success_color = "C2C287"
warning_color = "FFB627"

[purple_haze]
name = "Purple Haze"
description = "Deep purple theme with cosmic vibes"
background_color = "1A0B2E"
text_color = "E5E3F0"
selected_color = "7209B7"
secondary_color = "2D1B3D"
accent_color = "A663CC"
error_color = "FF6B9D"
success_color = "4ECDC4"
warning_color = "FFE66D"

[matrix]
name = "Matrix Green"
description = "Classic Matrix movie theme"
background_color = "000000"
text_color = "00FF00"
selected_color = "008F11"
secondary_color = "001100"
accent_color = "39FF14"
error_color = "FF1100"
success_color = "00AA00"
warning_color = "FFFF00"