# GJTV Theme Configuration
# Define color schemes and visual themes

[default]
name = "GJTV Default"
description = "Default dark theme with warm accents"
background_color = "2E282A"
text_color = "FFFFFF" 
selected_color = "D6BA73"
secondary_color = "4A4A4A"
accent_color = "D6BA73"
error_color = "E06C75"
success_color = "98C379"
warning_color = "E5C07B"
cell_background_color = "3A3A3A"
cell_border_color = "5A5A5A"
tab_background_color = "404040"
tab_border_color = "606060"
tab_active_color = "D6BA73"
tab_inactive_color = "2A2A2A"

[dark_blue]
name = "Dark Blue"
description = "Professional dark blue theme"
background_color = "1E1E2E"
text_color = "CDD6F4"
selected_color = "89B4FA"
secondary_color = "313244"
accent_color = "89B4FA"
error_color = "F38BA8"
success_color = "A6E3A1"
warning_color = "F9E2AF"
cell_background_color = "313244"
cell_border_color = "585B70"
tab_background_color = "45475A"
tab_border_color = "6C7086"
tab_active_color = "89B4FA"
tab_inactive_color = "1E1E2E"

[nord]
name = "Nord"
description = "Nord color scheme inspired theme"
background_color = "2E3440"
text_color = "ECEFF4"
selected_color = "88C0D0"
secondary_color = "3B4252"
accent_color = "5E81AC"
error_color = "BF616A"
success_color = "A3BE8C"
warning_color = "EBCB8B"
cell_background_color = "3B4252"
cell_border_color = "4C566A"
tab_background_color = "434C5E"
tab_border_color = "5E81AC"
tab_active_color = "88C0D0"
tab_inactive_color = "2E3440"

[dracula]
name = "Dracula"
description = "Popular Dracula theme colors"
background_color = "282A36"
text_color = "F8F8F2"
selected_color = "BD93F9"
secondary_color = "44475A"
accent_color = "FF79C6"
error_color = "FF5555"
success_color = "50FA7B"
warning_color = "F1FA8C"
cell_background_color = "44475A"
cell_border_color = "6272A4"
tab_background_color = "44475A"
tab_border_color = "8BE9FD"
tab_active_color = "BD93F9"
tab_inactive_color = "282A36"

[gruvbox_dark]
name = "Gruvbox Dark"
description = "Warm and cozy Gruvbox dark theme"
background_color = "282828"
text_color = "EBDBB2"
selected_color = "FABD2F"
secondary_color = "3C3836"
accent_color = "FE8019"
error_color = "FB4934"
success_color = "B8BB26"
warning_color = "FABD2F"
cell_background_color = "3C3836"
cell_border_color = "504945"
tab_background_color = "3C3836"
tab_border_color = "BDAE93"
tab_active_color = "FABD2F"
tab_inactive_color = "282828"

[catppuccin_mocha]
name = "Catppuccin Mocha"
description = "Soothing pastel theme"
background_color = "1E1E2E"
text_color = "CDD6F4"
selected_color = "F5C2E7"
secondary_color = "313244"
accent_color = "CBA6F7"
error_color = "F38BA8"
success_color = "A6E3A1"
warning_color = "F9E2AF"
cell_background_color = "313244"
cell_border_color = "585B70"
tab_background_color = "45475A"
tab_border_color = "F5C2E7"
tab_active_color = "CBA6F7"
tab_inactive_color = "1E1E2E"

[tokyo_night]
name = "Tokyo Night"
description = "Modern Tokyo Night theme"
background_color = "1A1B26"
text_color = "C0CAF5"
selected_color = "7AA2F7"
secondary_color = "24283B"
accent_color = "BB9AF7"
error_color = "F7768E"
success_color = "9ECE6A"
warning_color = "E0AF68"
cell_background_color = "24283B"
cell_border_color = "414868"
tab_background_color = "32344A"
tab_border_color = "7AA2F7"
tab_active_color = "BB9AF7"
tab_inactive_color = "1A1B26"

[solarized_dark]
name = "Solarized Dark"
description = "Classic Solarized dark theme"
background_color = "002B36"
text_color = "839496"
selected_color = "268BD2"
secondary_color = "073642"
accent_color = "2AA198"
error_color = "DC322F"
success_color = "859900"
warning_color = "B58900"
cell_background_color = "073642"
cell_border_color = "586E75"
tab_background_color = "073642"
tab_border_color = "93A1A1"
tab_active_color = "268BD2"
tab_inactive_color = "002B36"

[high_contrast]
name = "High Contrast"
description = "High contrast theme for accessibility"
background_color = "000000"
text_color = "FFFFFF"
selected_color = "FFFF00"
secondary_color = "333333"
accent_color = "00FFFF"
error_color = "FF0000"
success_color = "00FF00"
warning_color = "FFAA00"
cell_background_color = "333333"
cell_border_color = "FFFFFF"
tab_background_color = "333333"
tab_border_color = "FFFFFF"
tab_active_color = "FFFF00"
tab_inactive_color = "000000"

[light]
name = "Light Theme"
description = "Clean light theme for bright environments"
background_color = "FFFFFF"
text_color = "2E3440"
selected_color = "5E81AC"
secondary_color = "ECEFF4"
accent_color = "88C0D0"
error_color = "BF616A"
success_color = "A3BE8C"
warning_color = "D08770"
cell_background_color = "ECEFF4"
cell_border_color = "D8DEE9"
tab_background_color = "E5E9F0"
tab_border_color = "5E81AC"
tab_active_color = "88C0D0"
tab_inactive_color = "FFFFFF"

[gaming]
name = "Gaming RGB"
description = "Vibrant gaming-inspired theme"
background_color = "0D1117"
text_color = "F0F6FC"
selected_color = "00D8FF"
secondary_color = "21262D"
accent_color = "FF6B6B"
error_color = "FF4757"
success_color = "2ED573"
warning_color = "FFA502"
cell_background_color = "21262D"
cell_border_color = "30363D"
tab_background_color = "21262D"
tab_border_color = "FF6B6B"
tab_active_color = "00D8FF"
tab_inactive_color = "0D1117"

[retro]
name = "Retro CRT"
description = "Nostalgic retro computer theme"
background_color = "001100"
text_color = "00FF41"
selected_color = "FFFF00"
secondary_color = "003300"
accent_color = "00FFFF"
error_color = "FF4444"
success_color = "44FF44"
warning_color = "FFAA00"
cell_background_color = "003300"
cell_border_color = "00FF41"
tab_background_color = "003300"
tab_border_color = "00FFFF"
tab_active_color = "FFFF00"
tab_inactive_color = "001100"

[ocean]
name = "Ocean Blue"
description = "Calming ocean-inspired theme"
background_color = "0F3460"
text_color = "E8F4FD"
selected_color = "16537E"
secondary_color = "1E5F8A"
accent_color = "5DADE2"
error_color = "E74C3C"
success_color = "27AE60"
warning_color = "F39C12"
cell_background_color = "1E5F8A"
cell_border_color = "2E86AB"
tab_background_color = "1E5F8A"
tab_border_color = "5DADE2"
tab_active_color = "16537E"
tab_inactive_color = "0F3460"

[sunset]
name = "Sunset Orange"
description = "Warm sunset colors"
background_color = "2C1810"
text_color = "F4E7DA"
selected_color = "FF6B35"
secondary_color = "4A2C1A"
accent_color = "FF8C42"
error_color = "E85A4F"
success_color = "C2C287"
warning_color = "FFB627"
cell_background_color = "4A2C1A"
cell_border_color = "6B3E2A"
tab_background_color = "4A2C1A"
tab_border_color = "FF8C42"
tab_active_color = "FF6B35"
tab_inactive_color = "2C1810"

[purple_haze]
name = "Purple Haze"
description = "Deep purple theme with cosmic vibes"
background_color = "1A0B2E"
text_color = "E5E3F0"
selected_color = "7209B7"
secondary_color = "2D1B3D"
accent_color = "A663CC"
error_color = "FF6B9D"
success_color = "4ECDC4"
warning_color = "FFE66D"
cell_background_color = "2D1B3D"
cell_border_color = "432B4F"
tab_background_color = "2D1B3D"
tab_border_color = "A663CC"
tab_active_color = "7209B7"
tab_inactive_color = "1A0B2E"

[matrix]
name = "Matrix Green"
description = "Classic Matrix movie theme"
background_color = "000000"
text_color = "00FF00"
selected_color = "008F11"
secondary_color = "001100"
accent_color = "39FF14"
error_color = "FF1100"
success_color = "00AA00"
warning_color = "FFFF00"
cell_background_color = "001100"
cell_border_color = "00FF00"
tab_background_color = "001100"
tab_border_color = "39FF14"
tab_active_color = "008F11"
tab_inactive_color = "000000"